name: task_2023
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit:
  flutter_riverpod:
  flutter_screenutil:
  dio:
  hive:
  hive_flutter:
  flutter_launcher_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true